# fly.toml app configuration file generated for uplify on 2024-11-21T12:10:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uplify'
primary_region = 'lhr'
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
   memory = "1gb"
  
[env]
NODE_OPTIONS='--max-old-space-size=4096'


